export const riskRules = Object.freeze({
  thresholds: { medium: 35, high: 70 },
  dangerousClasses: {
    gun: { label: '枪支', weight: 65 },
    firearm: { label: '枪支', weight: 65 },
    枪支: { label: '枪支', weight: 65 },
    explosive: { label: '爆炸物', weight: 65 },
    bomb: { label: '爆炸物', weight: 65 },
    爆炸物: { label: '爆炸物', weight: 65 },
    knife: { label: '刀具', weight: 45 },
    gongju_agnostic: { label: '工具类物品', weight: 34 },
    knife_agnostic: { label: '疑似刀具', weight: 45 },
    pressure_agnostic: { label: '压力容器', weight: 34 },
    scissor: { label: '剪刀', weight: 36 },
    powerbank: { label: '充电宝', weight: 28 },
    bottle: { label: '瓶装液体', weight: 25 },
    刀具: { label: '刀具', weight: 45 },
    lighter: { label: '打火机', weight: 38 },
    打火机: { label: '打火机', weight: 38 },
    aerosol: { label: '压力容器', weight: 32 },
    压力容器: { label: '压力容器', weight: 32 },
    flammable_liquid: { label: '疑似易燃液体', weight: 48 },
    易燃液体: { label: '疑似易燃液体', weight: 48 },
  },
  confidence: { minimum: 0.3, high: 0.8 },
  gas: {
    alarmWeight: 38,
    risingWeight: 10,
    abnormalConcentrationWeight: 18,
    extremeConcentrationWeight: 35,
    thresholds: { combustible: 100, voc: 50, co: 35, smoke: 80, default: 100 },
  },
  evidenceSynergyWeight: 18,
  sensorUnavailableWeight: 20,
  noEffectiveDataScore: 35,
});
